### ISSUE TITLE
JOSS: Review comments [Software Paper]

### ISSUE THREAD

**Issue by HaoZeke** [JuliaSmoothOptimizers/PDENLPModels.jl#87]
As written, I'm afraid I do not see any reason that a thin compatibility layer to the already published Gridap should go forward. Please expand the paper with design and implementation considerations.

**Comment by tmigot** [comment]
Review for JOSS: https://github.com/openjournals/joss-reviews/issues/4736 Dear @HaoZeke @jbytecode 

We do not believe that PDENLPModels qualifies as a thin wrapper of Gridap. Gridap focuses on partial differential equations (only), so that only the derivative of the PDE w.r.t to its solution is available, while PDENLPModels deals with optimization problems (where the PDE is a constraint only) and gives access to the first and second derivatives w.r.t. to the solution of the PDE, the control function and the finite-dimensional variable.

In our opinion, the package respects JOSS's Substantial scholarly effort policy https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort .
The package is feature-complete, the source folder of the packages currently contains 2500 lines of code, designed for maintainable extensions (as we plan to add alternative finite-elements approaches), and offers a significant contribution to the available open-source software as stated in the Statement of need section in the paper.

To make, the contribution of the package clearer w.r.t to Gridap.jl we suggest the following modification: #88

**Comment by jbytecode** [comment]
Due to the JOSS submission: https://github.com/openjournals/joss-reviews/issues/4736

**Comment by HaoZeke** [comment]
I'm afraid I am still a little concerned. In part this is because the [NLPModels themselves](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/main/CITATION.bib), along with the [other wrappers implementing this API](https://juliasmoothoptimizers.github.io/NLPModels.jl/dev/models/) them do not seem to be published. Additionally, LOC is a poor metric, and there is no need (IMO) to nitpick about the code quality in particular (how many lines are code, etc.). It would help to have more than two examples, including an example of extensibility as mentioned.

There are still unfortunately several reasons why then, I'm not sure this is not a "thin" wrapper of existing API implementations, none of which have found the impetus perhaps to be shepherded through JOSS.
